<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
A   = [[1, 3, 4],
       [2, 5, 7],
       [5, 9, 6]]
B   = [[1, 0, 0],
       [0, 1 ,0],
       [0 ,0, 1]]
A1   = [[1, 2],
       [3, 4]]
B1   = [[1, 2, 3, 4, 5],
       [5, 6 ,7 ,8 ,9]]
A2   = [[1, 2],
       [3, 4]]
B2   = [[1, 4],
      [5, 6],
      [7, 8],
      [9, 6]]

def matrixmult (A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
      print("A*B =Not possible.")
      return

    # Create the result matrix
    # Dimensions would be rows_A x cols_B
    C = [[0 for row in range(cols_B)] for col in range(rows_A)]
   # print(C)

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i][j] += A[i][k] * B[k][j]
    for c in C:
       print(c)

   
print("First matrix")
matrixmult(A, B)
print("Second matrix")
matrixmult(A1,B1)
print("Third matrix")
matrixmult(A2,B2)


First matrix
[1, 3, 4]
[2, 5, 7]
[5, 9, 6]
Second matrix
[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]
Third matrix
A*B =Not possible.


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [0]:
from random import uniform
from random import choices
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure

A = [0,5,27,6,13,28,100,45,10,79]
def pick_a_number_from_list(A):
  sum=0
  for i in range(len(A)):
    sum = sum + A[i]
  c_dash=[]
  for i in range(len(A)):
    c_dash.append(A[i]/sum)
  #Cummulative sum
  c_bar=[]
  for i in range(len(A)):
    c_bar.append(0)
  #c_bar=0
  for i in range(len(A)):
    c_bar[i]=c_dash[i]+c_bar[i]
  r = uniform(0.0,1.0)
  number=0
  print("Random Numer",r)
 # print("C-bar",c_bar)
  x = choices(A,c_bar,k=100)

  print(x)
   

def sampling_based_on_magnitued():
  pick_a_number_from_list(A)

   
sampling_based_on_magnitued()

Random Numer 0.11296054000663958
[27, 100, 100, 45, 100, 100, 100, 27, 28, 100, 6, 27, 100, 79, 28, 79, 100, 79, 100, 45, 45, 79, 79, 79, 45, 13, 5, 6, 100, 79, 28, 79, 100, 79, 100, 100, 27, 27, 45, 100, 45, 100, 100, 13, 27, 45, 28, 100, 28, 100, 79, 45, 79, 45, 100, 10, 79, 27, 79, 79, 45, 45, 100, 45, 100, 79, 6, 27, 100, 79, 100, 45, 100, 10, 45, 100, 100, 45, 27, 45, 45, 27, 45, 79, 79, 27, 27, 13, 100, 79, 10, 79, 100, 79, 100, 79, 45, 45, 79, 28]


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [0]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
String = input ("Enter numeric string :") 
def replace_digits(String):
  # write your code
   # 
  result = re.sub(r"[a-z]", "", String, flags=re.I)
  result1 = re.sub(r"[0-9]", "#", result, flags=re.I)
  print("Output :",result1)
#  return() # modified string which is after replacing the # with digits

replace_digits(String)


Enter numeric string :234fgh6
Output : ####


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# number of elemetns as input 
n = int(input("Enter number of elements : ")) 

students=[]
for num in range(n):
    x=str(input("Enter name of students: "))
    students.append(x)

marks=[]
for num1 in range(n):
    y=int(input("Enter marks of students:"))
    marks.append(y)

#print(students,marks)
#students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
#marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
def display_dash_board(students, marks):

    # write code for computing top top 5 students
    dictionary = dict(zip(students,marks))
    print("top 5 ranks, in the descending order of marks ")
    for key, value in sorted(dictionary.items(), key=lambda item: item[1],reverse=True)[:5]:
      print("%s: %s" % (key, value))
      top_5_students = (key, value)
    # write code for computing top least 5 students
    print("least 5 ranks, in the increasing order of marks")
    for key, value in sorted(dictionary.items(), key=lambda item: item[1])[:5]:
      print("%s: %s" % (key, value))
    #  least_5_students = (key, value)
    # write code for computing top least 5 students
    print("marks between >25th percentile <75th percentile, in the increasing order of marks")
    for key, value in sorted(dictionary.items(), key=lambda item: item[1]):
      percentage = value * 100.0 / 100 
      if 25 < percentage < 75 :
        print("%s: %s : %d" % (key, value, percentage))
     #   students_within_25_and_75 = (key, value, percentage)
    
    #return top_5_students, least_5_students, students_within_25_and_75

display_dash_board(students, marks)



Enter number of elements : 10
Enter name of students: t1
Enter name of students: t2
Enter name of students: t3
Enter name of students: t4
Enter name of students: t5
Enter name of students: t6
Enter name of students: t7
Enter name of students: t8
Enter name of students: t9
Enter name of students: t10
Enter marks of students:45
Enter marks of students:78
Enter marks of students:12
Enter marks of students:14
Enter marks of students:48
Enter marks of students:3
Enter marks of students:47
Enter marks of students:98
Enter marks of students:35
Enter marks of students:80
top 5 ranks, in the descending order of marks 
t8: 98
t10: 80
t2: 78
t5: 48
t7: 47
least 5 ranks, in the increasing order of marks
t6: 3
t3: 12
t4: 14
t9: 35
t1: 45
marks between >25th percentile <75th percentile, in the increasing order of marks
t9: 35 : 35
t1: 45 : 45
t7: 47 : 47
t5: 48 : 48


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [0]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure
x = [1, 3, -1,6,0,-5,-1,6,1]
y = [2, 4, 1,-7,6,-8,-1,0,-1]
S = list(zip(x,y))
print(S)
P=(3,-4)
print(P)
x=[lis[0] for lis in S]
y=[lis[1] for lis in S]
p=P[0]
q=P[1]
print("X",x)
print("Y",y)
print("P",p)
print("q",q)
m=[]
i=0
for i in range(7):
  m=math.acos((x[i]*p+y[i]*q)/((math.sqrt((x[i]*x[i])+y[i]*y[i])*math.sqrt(p*p+q*q))))
  print(m)

print(', '.join('{:0.2f}'.format(i) for i in m))

# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    return closest_points_to_p  # its list of tuples

#S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
#P= (3,-4)
#points = closest_points_to_p(S, P)
print() #print the returned values

[(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
(3, -4)
X [1, 3, -1, 6, 0, -5, -1, 6, 1]
Y [2, 4, 1, -7, 6, -8, -1, 0, -1]
P 3
q -4
2.0344439357957027
1.8545904360032246
2.9996955989856287
0.06512516333438509
2.498091544796509
1.2021004241368467
1.4288992721907328


TypeError: ignored

<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [0]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print() # the returned value

<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [33]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
  blank_count=0
  value_count = 0
  sequenceNumber = 0
  splitString = string.split(",")
  print("Input:",string)
  #print(string)
  print(splitString)
  totalNumbers = len(splitString)
  for i in range(1,len(splitString)):
    print(i)
    if a[i]=="_":

      blank_count+=1
      print("AAA")
    else :
      print("Anoop")
      value_count=int(i)+int(value_count)
    sequenceNumber = int(value_count/totalNumbers)
    print(sequenceNumber)
    lst1=[]  
    for i in range(totalNumbers):
      lst1.append(str(sequenceNumber))
      lst2=','.join(lst1)
    # your code
    return lst2

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

Input: _,_,30,_,_,_,50,_,_
['_', '_', '30', '_', '_', '_', '50', '_', '_']
1


TypeError: ignored

<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions

A = [[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]
compute_conditional_probabilites(A)

<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [16]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):

    # your code
  S1_words = set(S1.split())
  S2_words = set(S2.split())
  common=S1_words & S2_words
  a=len(common)
  b=S1_words - S2_words
  c=S2_words - S1_words
  return a,b,c
  

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
{'5', 'F', 'first'}
{'S', 'second', '3'}


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [14]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):

    # your code
  logLoss = sum([int(A[i][0])*math.log10(float(A[i][1]))+ (1-int(A[i][0]))*math.log10(1-float(A[i][1])) for i in range(len(A))])
  logLoss = logLoss * -1/(len(A))
  return logLoss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print("Loss function ",loss)

Loss function  0.42430993457031635
